# metadata
site_name: ldap2pg documentation
site_description: Synchronise Postgres roles from LDAP directory
site_author: Dalibo Labs
site_url: https://ldap2pg.readthedocs.io/
copyright: © Dalibo 2017-2020
repo_name: ldap2pg
repo_url: https://github.com/dalibo/ldap2pg

theme:
  name: readthedocs

nav:
- Home: index.md
- Installation: install.md
- Configuration:
  - CLI: cli.md
  - ldap2pg.yml: config.md
  - Inspecting Cluster: postgres.md
  - Querying Directory: ldap.md
  - Managing Roles: roles.md
  - Managing Privileges: privileges.md
  - Well-known Privileges: wellknown.md
- API: api.md
- Cookbook: cookbook.md
- Hacking: hacking.md
- Changelog: changelog.md

site_dir: build/docs/

# Markdown settings
markdown_extensions:
- admonition
- fenced_code
- sane_lists
- smarty
- toc:
    baselevel: 2
    permalink: yes
- wikilinks
