version: 2

.unit_tpl: &unit_tpl
  working_directory: ~/ldap2pg
  steps:
  - checkout
  - restore_cache:
      keys: [ldap2pg]
  - run: |
      sudo pip install wheel virtualenv
      virtualenv .venv/
      . .venv/bin/activate
      pip install -U -r requirements-ci.txt -e .
  - save_cache:
      key: ldap2pg
      paths:
      - "~/.cache/pip/"
      - ".venv"
  - run: |
      . .venv/bin/activate
      flake8 .
      python setup.py --long-description | rst2html.py --strict >/dev/null
      pytest tests/unit/
      codecov

jobs:
  unit-py27:
    <<: *unit_tpl
    docker: [{image: "circleci/python:2.7"}]

  unit-py34:
    <<: *unit_tpl
    docker: [{image: "circleci/python:3.4"}]

  rpm:
    docker: [{image: "centos:7"}]
    working_directory: /tmp/ldap2pg
    steps:
    - checkout
    - run: ./packaging/build_rpm.sh
    - persist_to_workspace:
        root: /tmp/ldap2pg
        paths: ["dist/"]

workflows:
  version: 2
  pipeline:
    jobs:
    - unit-py27
    - unit-py34
    - rpm
