version: 2

.unit_tpl: &unit_tpl
  working_directory: ~/ldap2pg
  steps:
  - checkout
  - restore_cache:
      keys: [ldap2pg]
  - run: |
      sudo pip install wheel virtualenv
      virtualenv .venv/
      . .venv/bin/activate
      pip install -U -r requirements-ci.txt -e .
  - save_cache:
      key: ldap2pg
      paths:
      - "~/.cache/pip/"
      - ".venv"
  - run: |
      . .venv/bin/activate
      flake8 .
      python setup.py --long-description | rst2html.py --strict >/dev/null
      pytest tests/unit/
      codecov

jobs:
  unit-py27:
    <<: *unit_tpl
    docker: [{image: "circleci/python:2.7"}]

  unit-py34:
    <<: *unit_tpl
    docker: [{image: "circleci/python:3.4"}]

workflows:
  version: 2
  pipeline:
    jobs:
    - unit-py27
    - unit-py34
