version: 2

.unit_tpl: &unit_tpl
  working_directory: ~/ldap2pg
  steps:
  - checkout
  - restore_cache:
      keys: [ldap2pg]
  - run: |
      sudo pip install wheel virtualenv
      virtualenv .venv/
      . .venv/bin/activate
      pip install -U -r requirements-ci.txt -e .
  - save_cache:
      key: ldap2pg
      paths:
      - "~/.cache/pip/"
      - ".venv"
  - run: |
      . .venv/bin/activate
      sort --check .gitignore
      flake8 . tests/*/
      python setup.py --long-description | rst2html.py --strict >/dev/null
      pytest tests/unit/
      codecov

jobs:
  0-docs:
    docker: [{image: "circleci/python:3.4"}]
    working_directory: ~/ldap2pg
    steps:
    - checkout
    - restore_cache:
        keys: [ldap2pg]
    - run: |
        sudo pip install wheel virtualenv
        virtualenv .venv/
        . .venv/bin/activate
        pip install -U -r requirements-ci.txt -e .
    - save_cache:
        key: ldap2pg
        paths:
        - "~/.cache/pip/"
        - ".venv"
    - run: |
        . .venv/bin/activate
        mkdocs build --clean --strict

  0-unit-py27:
    <<: *unit_tpl
    docker: [{image: "circleci/python:2.7"}]

  0-unit-py34:
    <<: *unit_tpl
    docker: [{image: "circleci/python:3.4"}]

  0-rpm:
    docker: [{image: "centos:7"}]
    working_directory: /tmp/ldap2pg
    steps:
    - checkout
    - run: ./packaging/build_rpm.sh
    - persist_to_workspace:
        root: /tmp/ldap2pg
        paths: ["dist/"]
    - store_artifacts:
        path: /tmp/ldap2pg/dist/

  1-func-centos7:
    working_directory: /tmp/ldap2pg
    docker:
      - image: centos:7
      - image: dinkel/openldap:latest
        environment:
          SLAPD_PASSWORD: communication
          SLAPD_DOMAIN: ldap2pg.local
      - image: postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: communication
    steps:
    - checkout
    - run:
        name: Clean checkout from embedded circleci git client
        command: |
          yum install -y git
          git clean -df
    - attach_workspace:
        at: /tmp/ldap2pg/
    - run:
        name: Exécuting functionnal tests
        command: |
          export PGHOST=localhost PGUSER=postgres PGPASSWORD=communication
          export LDAPHOST=localhost LDAPBINDDN=cn=admin,dc=ldap2pg,dc=local LDAPPASSWORD=communication
          tests/func/entrypoint.sh

workflows:
  version: 2
  pipeline:
    jobs:
    - 0-docs
    - 0-unit-py27
    - 0-unit-py34
    - 0-rpm
    - 1-func-centos7:
        requires: [0-unit-py27, 0-rpm]
